
def BINARY_SEARCH(TARGET, BOTTOM, MIDDLE, TOP, NUM_LIST):
    if TOP == BOTTOM:
        return -1
    if TARGET == NUM_LIST[MIDDLE]:
        return MIDDLE
    elif TARGET > NUM_LIST[MIDDLE]:
        return BINARY_SEARCH(TARGET, MIDDLE + 1, (BOTTOM + TOP) // 2, TOP, NUM_LIST)
    elif TARGET < NUM_LIST[MIDDLE]:
        return BINARY_SEARCH(TARGET, BOTTOM, (BOTTOM + TOP) // 2, MIDDLE - 1, NUM_LIST)


NUM_LIST = [2, 3, 6, 7, 9, 15, 21]

BOTTOM = 0
TOP = len(NUM_LIST) - 1
MIDDLE = (BOTTOM + TOP) // 2

TARGET = 0

print(BINARY_SEARCH(TARGET, BOTTOM, MIDDLE, TOP, NUM_LIST))